default_platform(:android)

platform :android do
  desc "Build"
  lane :build do
    gradle(task: "clean")
    gradle(
      task: "app:phone:assemble",
      flavor: "libre",
      build_type: "release",
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => ENV["FINDROID_KEYSTORE"],
        "android.injected.signing.store.password" => ENV["FINDROID_KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["FINDROID_KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["FINDROID_KEY_PASSWORD"],
      }
    )

    gradle(
      task: "app:phone:bundle",
      flavor: "libre",
      build_type: "release",
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => ENV["FINDROID_KEYSTORE"],
        "android.injected.signing.store.password" => ENV["FINDROID_KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["FINDROID_KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["FINDROID_KEY_PASSWORD"],
      }
    )

  end
end
