name: Build

on: [push]

jobs:
  build:
    name: Build Release APKs
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Decode keystore file
        uses: timheuer/base64-to-file@v1
        id: findroid_keystore
        with:
          fileName: 'findroid-keystore.jks'
          encodedString: ${{ secrets.FINDROID_KEYSTORE }}

      - name: Build Release APKs
        run: bundle exec fastlane build
        env:
          FINDROID_KEYSTORE: ${{ steps.findroid_keystore.outputs.filePath }}
          FINDROID_KEYSTORE_PASSWORD: ${{ secrets.FINDROID_KEYSTORE_PASSWORD }}
          FINDROID_KEY_ALIAS: ${{ secrets.FINDROID_KEY_ALIAS }}
          FINDROID_KEY_PASSWORD: ${{ secrets.FINDROID_KEY_PASSWORD }}

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-apks
          path: ./app/phone/build/outputs/apk/libre/release/*.apk